# Generated by Django 5.2 on 2025-04-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_title', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('Author', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField()),
                ('Status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')])),
            ],
        ),
    ]
