# Generated by Django 5.1.5 on 2025-04-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], max_length=100),
        ),
    ]
